# This file is automatically generated from cmake-kits.json and should be modified only if compiling from CLI
if (NOT DEFINED ENV{ARMGCC_DIR})
	SET(ARMGCC_DIR /home/teleport/.mcuxpressotools/arm-gnu-toolchain-12.2.rel1-x86_64-arm-none-eabi)
endif()
